name: Renovate template config CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'default.json'

jobs:
  build:
    uses: chalharu/workflows/.github/workflows/renovate-ci.yaml@7548b46a59ba9d03fd4cdf12e485e36692eac003 # main
    with:
      target: default.json
