name: Renovate template config CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'default.json'

jobs:
  build:
    uses: chalharu/workflows/.github/workflows/renovate-ci.yaml@83147cc41dac14fe17001047ab14bf87db11b50f # main
    with:
      target: default.json
