name: Renovate config CI

on:
  pull_request:
    paths:
      - 'renovate.json'
      - 'renovate.json5'
      - '.github/renovate.json'
      - '.github/renovate.json5'
      - '.gitlab/renovate.json'
      - '.gitlab/renovate.json5'
      - '.renovaterc'
      - '.renovaterc.json'
      - '.renovaterc.json5'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Use Node.js
      uses: actions/setup-node@v4.1.0
      with:
        node-version: lts/*
        check-latest: true
    - name: renovate test
      run: npx --yes --package renovate -- renovate-config-validator --strict default.json
