name: Renovate template config CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'default.json'

jobs:
  build:
    uses: ./.github/workflows/ci-config-base.yaml
    with:
      target: default.json
