name: Renovate template config CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'default.json'

jobs:
  build:
    uses: chalharu/workflows/.github/workflows/renovate-ci.yaml@main
    with:
      target: default.json
